### ISSUE TITLE
deferred stacktraces  (`getStackTrace(e: ref Exception)`) don't work (works with standard nim stacktraces)

### ISSUE THREAD

**Issue by timotheecour** [status-im/nim-libbacktrace#5]
standard nim stacktraces allow getting stacktraces stored in an Exception (eg for use in a catch statement); but libbacktrace ones don't work in this case (they only work in non-deferred mode, eg when crashing with `doAssert false`), so it's not a suitable replacement for standard stacktraces at the moment.

I had originally opened https://github.com/status-im/nim-libbacktrace/issues/4 as I assumed the code did "eager" symbolication which is not efficient but in fact I now realize it doesn't do any symbolication at all for caught exceptions; **feel free to close either this issue or https://github.com/status-im/nim-libbacktrace/issues/4 if you consider them duplicates** (although https://github.com/status-im/nim-libbacktrace/issues/4 deals with performance and this one deals with correctness).

As I mentioned in https://github.com/status-im/nim-libbacktrace/issues/4, one way to fix this would be using something like what D does (https://github.com/dlang/druntime/blob/master/src/rt/backtrace/dwarf.d) which collects backtrace (cheap) then symbolicates if needed later. However it's not yet clear to me whether libbacktrace supports deferred symbolication (see https://github.com/ianlancetaylor/libbacktrace/issues/35)

## example
```
# standard nim stacktraces: works (shows a stacktrace)
nim c -r --stacktrace:on -d:case2c -g $timn_D/tests/nim/all/t10308.nim

# libbacktrace stacktraces: doesn't work (shows empty stacktrace)
nim c -r --stacktrace:off -d:nimStackTraceOverride --import:libbacktrace -g main.nim
```

```nim
# main.nim
proc fun() =
  # doAssert false # this works, correctly showing a stacktrace
  raise newException(CatchableError, "foo")
try: fun()
except CatchableError as e:
  echo "caught:\n" & e.getStacktrace() # BUG: no stacktrace shown
echo "after"
```

this outputs:
```
caught:

after
```
instead of showing a stacktrace, like in standard nim stacktraces

## links
D20200308T163130

**Comment by stefantalpalaru** [comment]
Fixed a few months ago.

**Comment by timotheecour** [comment]
confirmed, thanks!
